:Author: kooch123
:Email:
:Date: 14/08/2025
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== Libraries

I eleceted to try the SchedTask library here: https://github.com/Nospampls/SchedTask due
to the fact it has some nice youTube videos describing the library with code examples
and seemed pretty well thought out.


=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM






Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| 1 | Keyestudio.com 4-Channel Relay Module Shield | ks0251 | 1
| 2 | HiLetgo ZMCT103C 5A AC Current Sensor | X004034T6P | 1
| 3 | Passive Buzzer Module | https://www.amazon.com/dp/B0BSGW6CXM | 1



| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]


=== Workflow Thoughts:

every 4 hours, turn on the chiller and let it run until the chiller stops running as judged by the ammeter





